kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
    podSubnet: "10.244.0.0/16"
containerdConfigPatches:
    - |-
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
        endpoint = ["http://proxy:5000"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
        endpoint = ["http://registry:5000"]
nodes:
    - role: control-plane
      extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        listenAddress: "0.0.0.0"
      - containerPort: 30000
        hostPort: 30000
        listenAddress: "0.0.0.0"
      - containerPort: 30001
        hostPort: 30001
        listenAddress: "0.0.0.0"
      - containerPort: 30002
        hostPort: 30002
        listenAddress: "0.0.0.0"
      - containerPort: 30003
        hostPort: 30003
        listenAddress: "0.0.0.0"
      - containerPort: 30004
        hostPort: 30004
        listenAddress: "0.0.0.0"
      - containerPort: 30005
        hostPort: 30005
        listenAddress: "0.0.0.0"
      - containerPort: 30006
        hostPort: 30006
        listenAddress: "0.0.0.0"
      - containerPort: 30007
        hostPort: 30007
        listenAddress: "0.0.0.0"