apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: kubeedge
    kubeedge: edgemesh-gateway
spec:
  selector:
    matchLabels:
      k8s-app: kubeedge
      kubeedge: edgemesh-gateway
  template:
    metadata:
      labels:
        k8s-app: kubeedge
        kubeedge: edgemesh-gateway
    spec:
      {{- if (.Values.nodeName) }}
      nodeName: {{ .Values.nodeName }}
      {{- else }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      hostNetwork: true
      containers:
        - name: {{ .Release.Name }}
          securityContext:
            privileged: true
          image: {{ .Values.image }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
            - name: conf
              mountPath: /etc/edgemesh/config
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - name: psk
              mountPath: /etc/edgemesh
            {{- if .Values.metaServerSecret }}
            - name: metaserver-certs
              mountPath: /etc/edgemesh/metaserver
            {{- end }}
      restartPolicy: Always
      serviceAccountName: {{ .Release.Name }}
      volumes:
        - name: conf
          configMap:
            name: {{ .Release.Name }}-cfg
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: psk
          configMap:
            name: {{ .Release.Name }}-psk
        {{- if .Values.metaServerSecret }}
        - name: metaserver-certs
          secret:
            secretName: {{ .Values.metaServerSecret }}
            defaultMode: 420
        {{- end }}
