# Default values for kubeedge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appVersion: "1.9.5"

cloudCore:
  replicaCount: 1
  hostNetWork: "false"
  image:
    repository: "kubeedge/cloudcore"
    tag: "v1.9.5"
    pullPolicy: "IfNotPresent"
    imagePullSecrets: ["lcr"]
  securityContext:
    privileged: true
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
  annotations: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/edge
            operator: DoesNotExist
  tolerations: {}
  nodeSelector: {}
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 256Mi
  modules:
    cloudHub:
      # Causion!: Leave this entry to empty will cause CloudCore to exit abnormally once KubeEdge is enabled.
      # At least a public IP Address or an IP which can be accessed by edge nodes must be provided!
      advertiseAddress:
        - ""
      nodeLimit: "1000"
      websocket:
        enable: "true"
      quic:
        enable: "false"
        maxIncomingStreams: "10000"
      https:
        enable: "true"
    cloudStream:
      enable: "true"
    dynamicController:
      enable: "true"
    router:
      enable: "false"
  service:
    enable: "true"
    type: "NodePort"
    cloudhubNodePort: "30000"
    cloudhubQuicNodePort: "30001"
    cloudhubHttpsNodePort: "30002"
    cloudstreamNodePort: "30003"
    tunnelNodePort: "30004"

iptablesManager:
  enable: "false"
  mode: "external" # internal external
  hostNetWork: false
  image:
    repository: "kubeedge/iptables-manager"
    tag: "v1.9.5"
    pullPolicy: "IfNotPresent"
    imagePullSecrets: []
  securityContext:
    capabilities:
      add:
        - NET_ADMIN
        - NET_RAW
  labels:
    k8s-app: iptables-manager
    kubeedge: iptables-manager
  annotations: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/edge
            operator: DoesNotExist
  tolerations: {}
  nodeSelector: {}
  resources:
    limits:
      cpu: 200m
      memory: 50Mi
    requests:
      cpu: 100m
      memory: 25Mi
