apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-agent-cfg
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: kubeedge
    kubeedge: edgemesh-agent
data:
  edgemesh-agent.yaml: |-
    {{- if .Values.kubeAPIConfig }}
    kubeAPIConfig:
      {{- if .Values.kubeAPIConfig.burst }}
      burst: {{ .Values.kubeAPIConfig.burst }}
      {{- end }}
      {{- if .Values.kubeAPIConfig.contentType }}
      contentType: {{ .Values.kubeAPIConfig.contentType }}
      {{- end }}
      {{- if .Values.kubeAPIConfig.kubeConfig }}
      kubeConfig: {{ .Values.kubeAPIConfig.kubeConfig }}
      {{- end }}
      {{- if .Values.kubeAPIConfig.master }}
      master: {{ .Values.kubeAPIConfig.master }}
      {{- end }}
      {{- if .Values.kubeAPIConfig.qps }}
      qps: {{ .Values.kubeAPIConfig.qps }}
      {{- end }}
      {{- if .Values.kubeAPIConfig.metaServer }}
      metaServer:
        {{- if .Values.kubeAPIConfig.metaServer.server }}
        server: {{ .Values.kubeAPIConfig.metaServer.server }}
        {{- end }}
        {{- if .Values.kubeAPIConfig.metaServer.security }}
        security:
          {{- if .Values.kubeAPIConfig.metaServer.security.requireAuthorization }}
          requireAuthorization: {{ .Values.kubeAPIConfig.metaServer.security.requireAuthorization }}
          {{- end }}
          {{- if .Values.kubeAPIConfig.metaServer.security.insecureSkipTLSVerify }}
          insecureSkipTLSVerify: {{ .Values.kubeAPIConfig.metaServer.security.insecureSkipTLSVerify }}
          {{- end }}
          {{- if .Values.kubeAPIConfig.metaServer.security.tlsCaFile }}
          tlsCaFile: {{ .Values.kubeAPIConfig.metaServer.security.tlsCaFile }}
          {{- end }}
          {{- if .Values.kubeAPIConfig.metaServer.security.tlsCertFile }}
          tlsCertFile: {{ .Values.kubeAPIConfig.metaServer.security.tlsCertFile }}
          {{- end }}
          {{- if .Values.kubeAPIConfig.metaServer.security.tlsPrivateKeyFile }}
          tlsPrivateKeyFile: {{ .Values.kubeAPIConfig.metaServer.security.tlsPrivateKeyFile }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if .Values.kubeAPIConfig.deleteKubeConfig }}
      deleteKubeConfig: {{ .Values.kubeAPIConfig.deleteKubeConfig }}
      {{- end }}
    {{- end }}
    {{- if .Values.commonConfig }}
    commonConfig:
      {{- if .Values.commonConfig.bridgeDeviceName }}
      bridgeDeviceName: {{ .Values.commonConfig.bridgeDeviceName }}
      {{- end }}
      {{- if .Values.commonConfig.bridgeDeviceIP }}
      bridgeDeviceIP: {{ .Values.commonConfig.bridgeDeviceIP }}
      {{- end }}
    {{- end }}
    {{- if .Values.modules }}
    modules:
      {{- if .Values.modules.edgeDNS }}
      edgeDNS:
        {{- if .Values.modules.edgeDNS.enable }}
        enable: {{ .Values.modules.edgeDNS.enable }}
        {{- end }}
        {{- if .Values.modules.edgeDNS.listenPort }}
        listenPort: {{ .Values.modules.edgeDNS.listenPort }}
        {{- end }}
        {{- if .Values.modules.edgeDNS.cacheDNS }}
        cacheDNS:
          {{- if .Values.modules.edgeDNS.cacheDNS.enable }}
          enable: {{ .Values.modules.edgeDNS.cacheDNS.enable }}
          {{- end }}
          {{- if .Values.modules.edgeDNS.cacheDNS.autoDetect }}
          autoDetect: {{ .Values.modules.edgeDNS.cacheDNS.autoDetect }}
          {{- end }}
          {{- if .Values.modules.edgeDNS.cacheDNS.upstreamServers }}
          upstreamServers:
          {{- range .Values.modules.edgeDNS.cacheDNS.upstreamServers }}
          - {{ . | title }}
          {{- end }}
          {{- end }}
          {{- if .Values.modules.edgeDNS.cacheDNS.cacheTTL }}
          cacheTTL: {{ .Values.modules.edgeDNS.cacheDNS.cacheTTL }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if .Values.modules.edgeProxy }}
      edgeProxy:
        {{- if .Values.modules.edgeProxy.enable }}
        enable: {{ .Values.modules.edgeProxy.enable }}
        {{- end }}
        {{- if .Values.modules.edgeProxy.serviceFilterMode }}
        serviceFilterMode: {{ .Values.modules.edgeProxy.serviceFilterMode }}
        {{- end }}
        {{- if .Values.modules.edgeProxy.socks5Proxy }}
        socks5Proxy:
          {{- if .Values.modules.edgeProxy.socks5Proxy.enable }}
          enable: {{ .Values.modules.edgeProxy.socks5Proxy.enable }}
          {{- end }}
          {{- if .Values.modules.edgeProxy.socks5Proxy.listenPort }}
          listenPort: {{ .Values.modules.edgeProxy.socks5Proxy.listenPort }}
          {{- end }}
        {{- end }}
        {{- if .Values.modules.edgeProxy.loadBalancer }}
        loadBalancer:
          {{- if .Values.modules.edgeProxy.loadBalancer.consistentHash }}
          consistentHash:
            {{- if .Values.modules.edgeProxy.loadBalancer.consistentHash.partitionCount }}
            partitionCount: {{ .Values.modules.edgeProxy.loadBalancer.consistentHash.partitionCount }}
            {{- end }}
            {{- if .Values.modules.edgeProxy.loadBalancer.consistentHash.replicationFactor }}
            replicationFactor: {{ .Values.modules.edgeProxy.loadBalancer.consistentHash.replicationFactor }}
            {{- end }}
            {{- if .Values.modules.edgeProxy.loadBalancer.consistentHash.load }}
            load: {{ .Values.modules.edgeProxy.loadBalancer.consistentHash.load }}
            {{- end }}
          {{- end }}
        {{- end }}
        {{- if .Values.modules.edgeProxy.serviceFilterMode }}
        serviceFilterMode: {{ .Values.modules.edgeProxy.serviceFilterMode }}
        {{- end }}
      {{- end }}
      {{- if .Values.modules.edgeTunnel }}
      edgeTunnel:
        {{- if .Values.modules.edgeTunnel.enable }}
        enable: {{ .Values.modules.edgeTunnel.enable }}
        {{- end }}
        {{- if .Values.modules.edgeTunnel.listenPort }}
        listenPort: {{ .Values.modules.edgeTunnel.listenPort }}
        {{- end }}
        {{- if .Values.modules.edgeTunnel.transport }}
        transport: {{ .Values.modules.edgeTunnel.transport }}
        {{- end }}
        {{- if .Values.modules.edgeTunnel.rendezvous }}
        rendezvous: {{ .Values.modules.edgeTunnel.rendezvous }}
        {{- end }}
        {{- if .Values.modules.edgeTunnel.enableIpfsLog }}
        enableIpfsLog: {{ .Values.modules.edgeTunnel.enableIpfsLog }}
        {{- end }}
        {{- if .Values.relayNodes }}
        relayNodes:
        {{- range .Values.relayNodes }}
        - nodeName: {{ .nodeName }}
          advertiseAddress:
          {{- range .advertiseAddress }}
          - {{ . | title }}
          {{- end }}
        {{- end }}
        {{- end }}
        {{- if .Values.modules.edgeTunnel.maxCandidates }}
        maxCandidates: {{ .Values.modules.edgeTunnel.maxCandidates }}
        {{- end }}
        {{- if .Values.modules.edgeTunnel.heartbeatPeriod }}
        heartbeatPeriod: {{ .Values.modules.edgeTunnel.heartbeatPeriod }}
        {{- end }}
        {{- if .Values.modules.edgeTunnel.finderPeriod }}
        finderPeriod: {{ .Values.modules.edgeTunnel.finderPeriod }}
        {{- end }}
        {{- if .Values.modules.edgeTunnel.psk }}
        psk:
          {{- if .Values.modules.edgeTunnel.psk.enable }}
          enable: {{ .Values.modules.edgeTunnel.psk.enable }}
          {{- end }}
          {{- if .Values.modules.edgeTunnel.psk.path }}
          path: {{ .Values.modules.edgeTunnel.psk.path }}
          {{- end }}
        {{- end }}
        {{- if .Values.modules.edgeTunnel.tunnelLimitConfig }}
        tunnelLimitConfig:
          {{- if .Values.modules.edgeTunnel.tunnelLimitConfig.enable }}
          enable: {{ .Values.modules.edgeTunnel.tunnelLimitConfig.enable }}
          {{- end }}
          {{- if .Values.modules.edgeTunnel.tunnelLimitConfig.tunnelBaseStreamIn }}
          tunnelBaseStreamIn: {{ .Values.modules.edgeTunnel.tunnelLimitConfig.tunnelBaseStreamIn }}
          {{- end }}
          {{- if .Values.modules.edgeTunnel.tunnelLimitConfig.tunnelBaseStreamOut }}
          tunnelBaseStreamOut: {{ .Values.modules.edgeTunnel.tunnelLimitConfig.tunnelBaseStreamOut }}
          {{- end }}
          {{- if .Values.modules.edgeTunnel.tunnelLimitConfig.tunnelPeerBaseStreamIn }}
          tunnelPeerBaseStreamIn: {{ .Values.modules.edgeTunnel.tunnelLimitConfig.tunnelPeerBaseStreamIn }}
          {{- end }}
          {{- if .Values.modules.edgeTunnel.tunnelLimitConfig.tunnelPeerBaseStreamOut }}
          tunnelPeerBaseStreamOut: {{ .Values.modules.edgeTunnel.tunnelLimitConfig.tunnelPeerBaseStreamOut }}
          {{- end }}
        {{- end }}
        {{- if .Values.modules.edgeTunnel.listenInterfaces }}
        listenInterfaces: {{ .Values.modules.edgeTunnel.listenInterfaces }}
        {{- end }}
        {{- if .Values.modules.edgeTunnel.extraFilteredInterfaces }}
        extraFilteredInterfaces: {{ .Values.modules.edgeTunnel.extraFilteredInterfaces }}
        {{- end }}
      {{- end }}
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-agent-psk
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: kubeedge
    kubeedge: edgemesh-agent
data:
  psk: {{ .Values.psk }}
